import React, { useEffect, useState } from 'react';
import { ArrowLeft, Download, List } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { env } from '../../../app/config/env';

type GeneratedReportItem = {
  _id: string;
  reportCode: string;
  generatedByName?: string;
  createdAt: string;
  periodFrom: string;
  periodTo: string;
};

const formatDate = (value: string): string => {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '-';
  return date.toLocaleDateString('en-GB');
};

const downloadBlob = (blob: Blob, fileName: string) => {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
};

const GeneratedReportsPage: React.FC = () => {
  const navigate = useNavigate();
  const [reports, setReports] = useState<GeneratedReportItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchReports = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await fetch(`${env.API_URL}/reportGen/reports`);
      const data = await response.json();
      if (data.success) {
        setReports(data.data || []);
      } else {
        setError(data.message || 'Failed to load generated reports.');
      }
    } catch (err) {
      setError('Failed to load generated reports.');
    }
    setLoading(false);
  };

  useEffect(() => {
    fetchReports();
  }, []);

  const handleDownload = async (reportId: string, reportCode: string) => {
    try {
      const response = await fetch(`${env.API_URL}/reportGen/reports/${reportId}/download`);
      if (!response.ok) {
        throw new Error('Download failed');
      }
      const blob = await response.blob();
      downloadBlob(blob, `${reportCode}.pdf`);
    } catch (err) {
      setError('Failed to download report.');
    }
  };

  return (
    <div className="flex-1 bg-[#f8f9fc] min-h-screen p-8 md:p-12 flex flex-col font-sans">
      <div className="flex items-center gap-4 mb-8">
        <button
          className="w-[46px] h-[46px] rounded-full border-[2px] border-black flex items-center justify-center hover:bg-gray-100 transition-colors"
          onClick={() => navigate('/admin/reports')}
        >
          <ArrowLeft className="w-7 h-7 text-black" strokeWidth={2.5} />
        </button>
        <h1 className="text-[42px] font-black text-black tracking-tight">Generated Reports</h1>
      </div>

      <div className="bg-white rounded-2xl border border-gray-200 shadow-sm overflow-hidden">
        <div className="grid grid-cols-4 bg-[#f3f6fb] text-[#64748b] font-bold text-sm tracking-wide px-6 py-4">
          <div>REPORT ID</div>
          <div>GENERATED BY</div>
          <div>GENERATED DATE</div>
          <div className="text-center">ACTIONS</div>
        </div>

        {loading && <div className="px-6 py-8 text-gray-600">Loading reports...</div>}
        {error && <div className="px-6 py-8 text-red-600 font-semibold">{error}</div>}

        {!loading && !error && reports.length === 0 && (
          <div className="px-6 py-8 text-gray-500">No generated reports found.</div>
        )}

        {!loading && !error && reports.map((report) => (
          <div key={report._id} className="grid grid-cols-4 items-center px-6 py-5 border-t border-gray-100 text-black">
            <div className="font-bold text-[#2563eb]">{report.reportCode}</div>
            <div className="font-semibold">{report.generatedByName || 'Admin'}</div>
            <div className="font-semibold">{formatDate(report.createdAt)}</div>
            <div className="flex justify-center">
              <button
                type="button"
                className="p-2 rounded-lg hover:bg-gray-100 transition-colors"
                onClick={() => handleDownload(report._id, report.reportCode)}
                title="Download"
              >
                <Download className="w-5 h-5" />
              </button>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-6 text-sm text-gray-500 flex items-center gap-2">
        <List className="w-4 h-4" />
        Showing the reports saved in MongoDB report collection.
      </div>
    </div>
  );
};

export default GeneratedReportsPage;
