import { Table, type TableColumn } from "../../../components/ui/Table";
import type { Report } from "../types";
import { format } from "date-fns";
import { Download, FileText } from "lucide-react";
import { Button } from "../../../components/ui/Button";

interface ReportTableProps {
  reports: Report[];
  onDownload: (id: string) => void;
}

export default function ReportTable({ reports, onDownload }: ReportTableProps) {
  const columns: TableColumn<Report>[] = [
    {
      header: "Report Name",
      cell: (report) => (
        <div className="flex items-center gap-3">
          <div className="p-2 bg-slate-100 text-slate-600 rounded-lg">
            <FileText size={18} />
          </div>
          <span className="font-medium text-slate-900">
            {report.reportType} Report - {format(new Date(report.createdAt), "MMM yy")}
          </span>
        </div>
      ),
    },
    {
      header: "Type",
      cell: (report) => (
        <span className="text-[10px] font-bold text-slate-500 bg-slate-100 px-2 py-0.5 rounded border border-slate-200 uppercase tracking-wider">
          {report.reportType}
        </span>
      ),
    },
    {
      header: "Reporting Period",
      cell: (report) => (
        <span className="text-xs text-slate-600">
          {format(new Date(report.periodFrom), "PP")} - {format(new Date(report.periodTo), "PP")}
        </span>
      ),
    },
    {
      header: "Generated By",
      cell: (report) => (
        <span className="text-xs text-slate-500 font-mono">
          {report.generatedBy}
        </span>
      ),
    },
    {
      header: "Actions",
      className: "text-right",
      cell: (report) => (
        <Button
          variant="outline"
          size="sm"
          onClick={() => onDownload(report._id)}
          className="p-2 hover:bg-blue-50 rounded-lg transition-colors text-slate-400 hover:text-blue-600"
          title="Download PDF"
        >
          <Download size={18} />
        </Button>
      ),
    },
  ];

  return (
    <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden font-poppins">
      <Table 
        columns={columns} 
        data={reports} 
      />
    </div>
  );
}
