import { useState } from "react";
import { Table, type TableColumn } from "../../../components/ui/Table";
import type { Report } from "../types";
import { format } from "date-fns";
import { Download, FileText, Trash2, AlertTriangle } from "lucide-react";
import { Button } from "../../../components/ui/Button";
import ConfirmDialog from "../../../components/common/ConfirmDialog";

interface ReportTableProps {
  reports: Report[];
  onDownload: (id: string) => void;
  onDelete: (id: string) => void;
}

export default function ReportTable({ reports, onDownload, onDelete }: ReportTableProps) {
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [targetId, setTargetId] = useState<string | null>(null);

  const requestDelete = (id: string) => {
    setTargetId(id);
    setConfirmOpen(true);
  };

  const handleConfirmDelete = () => {
    if (targetId) onDelete(targetId);
    setConfirmOpen(false);
    setTargetId(null);
  };

  const handleCancelDelete = () => {
    setConfirmOpen(false);
    setTargetId(null);
  };

  const columns: TableColumn<Report>[] = [
    {
      header: "Report Name",
      cell: (report) => (
        <div className="flex items-center gap-3">
          <div className="p-2 bg-slate-100 text-slate-600 rounded-lg">
            <FileText size={18} />
          </div>
          <span className="font-medium text-slate-900">
            {report.reportType} Report -{" "}
            {report.createdAt && !isNaN(new Date(report.createdAt).getTime())
              ? format(new Date(report.createdAt), "MMM yy")
              : "N/A"}
          </span>
        </div>
      ),
    },
    {
      header: "Type",
      cell: (report) => (
        <span className="text-[10px] font-bold text-slate-500 bg-slate-100 px-2 py-0.5 rounded border border-slate-200 uppercase tracking-wider">
          {report.reportType}
        </span>
      ),
    },
    {
      header: "Reporting Period",
      cell: (report) => (
        <span className="text-xs text-slate-600">
          {report.periodFrom && !isNaN(new Date(report.periodFrom).getTime())
            ? format(new Date(report.periodFrom), "PP")
            : "N/A"}{" "}
          -{" "}
          {report.periodTo && !isNaN(new Date(report.periodTo).getTime())
            ? format(new Date(report.periodTo), "PP")
            : "N/A"}
        </span>
      ),
    },
    {
      header: "Generated By",
      cell: (report) => (
        <span className="text-xs text-slate-500 font-mono">
          {typeof report.generatedBy === "object"
            ? (report.generatedBy as any).name
            : report.generatedBy}
        </span>
      ),
    },
    {
      header: "Actions",
      className: "text-right",
      cell: (report) => (
        <div className="flex items-center justify-end gap-2">
          {/* Download */}
          <Button
            variant="outline"
            size="sm"
            onClick={() => onDownload(report._id)}
            className="p-2 h-9 w-9 hover:bg-blue-50 rounded-lg transition-colors text-slate-400 hover:text-blue-600"
            title="Download PDF"
          >
            <Download size={16} />
          </Button>

          {/* Delete */}
          <Button
            variant="outline"
            size="sm"
            onClick={() => requestDelete(report._id)}
            className="p-2 h-9 w-9 hover:bg-rose-50 rounded-lg transition-colors text-slate-400 hover:text-rose-600"
            title="Delete Report"
          >
            <Trash2 size={16} />
          </Button>
        </div>
      ),
    },
  ];

  return (
    <>
      <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden font-poppins">
        <Table columns={columns} data={reports} />
      </div>

      <ConfirmDialog
        open={confirmOpen}
        title="Delete Report?"
        description="This report will be permanently deleted and cannot be recovered. You can always generate a new one."
        confirmText="Yes, Delete"
        cancelText="Keep it"
        icon={<AlertTriangle size={32} />}
        onConfirm={handleConfirmDelete}
        onCancel={handleCancelDelete}
      />
    </>
  );
}
