export const ORDER_STATUS = {
  ORDER_PLACED: 'ORDER_PLACED',
  PICKUP_ASSIGNED: 'PICKUP_ASSIGNED',
  PICKUP_ON_THE_WAY: 'PICKUP_ON_THE_WAY',
  PICKUP_ARRIVED: 'PICKUP_ARRIVED',
  PICKED_UP: 'PICKED_UP',
  HANDED_OVER: 'HANDED_OVER',
  WASHING: 'WASHING',
  DRYING: 'DRYING',
  PROCESSING: 'PROCESSING',
  READY: 'READY',
  DELIVERY_ASSIGNED: 'DELIVERY_ASSIGNED',
  DELIVERY_ON_THE_WAY: 'DELIVERY_ON_THE_WAY',
  DELIVERY_ARRIVED: 'DELIVERY_ARRIVED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
} as const;

export type OrderStatus = typeof ORDER_STATUS[keyof typeof ORDER_STATUS];

export const ORDER_TYPES = {
  WASH: 'WASH',
  DRY: 'DRY',
  IRON: 'IRON',
} as const;

export type OrderType = typeof ORDER_TYPES[keyof typeof ORDER_TYPES];